// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: tracerpb/span.proto

package tracerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spans         []*Span                `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_tracerpb_span_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracerpb_span_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_tracerpb_span_proto_rawDescGZIP(), []int{0}
}

func (x *ExportRequest) GetSpans() []*Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

type ExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_tracerpb_span_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracerpb_span_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_tracerpb_span_proto_rawDescGZIP(), []int{1}
}

func (x *ExportResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type Span struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TraceId           uint64                 `protobuf:"varint,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId            uint64                 `protobuf:"varint,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ParentId          uint64                 `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name              string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	StartTimeUnixNano int64                  `protobuf:"varint,5,opt,name=start_time_unix_nano,json=startTimeUnixNano,proto3" json:"start_time_unix_nano,omitempty"`
	EndTimeUnixNano   int64                  `protobuf:"varint,6,opt,name=end_time_unix_nano,json=endTimeUnixNano,proto3" json:"end_time_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_tracerpb_span_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_tracerpb_span_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_tracerpb_span_proto_rawDescGZIP(), []int{2}
}

func (x *Span) GetTraceId() uint64 {
	if x != nil {
		return x.TraceId
	}
	return 0
}

func (x *Span) GetSpanId() uint64 {
	if x != nil {
		return x.SpanId
	}
	return 0
}

func (x *Span) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Span) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Span) GetStartTimeUnixNano() int64 {
	if x != nil {
		return x.StartTimeUnixNano
	}
	return 0
}

func (x *Span) GetEndTimeUnixNano() int64 {
	if x != nil {
		return x.EndTimeUnixNano
	}
	return 0
}

var File_tracerpb_span_proto protoreflect.FileDescriptor

const file_tracerpb_span_proto_rawDesc = "" +
	"\n" +
	"\x13tracerpb/span.proto\x12\btracerpb\"5\n" +
	"\rExportRequest\x12$\n" +
	"\x05spans\x18\x01 \x03(\v2\x0e.tracerpb.SpanR\x05spans\" \n" +
	"\x0eExportResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xc9\x01\n" +
	"\x04Span\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\x04R\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\x04R\x06spanId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\x04R\bparentId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12/\n" +
	"\x14start_time_unix_nano\x18\x05 \x01(\x03R\x11startTimeUnixNano\x12+\n" +
	"\x12end_time_unix_nano\x18\x06 \x01(\x03R\x0fendTimeUnixNano2I\n" +
	"\tCollector\x12<\n" +
	"\aCollect\x12\x17.tracerpb.ExportRequest\x1a\x18.tracerpb.ExportResponseB=Z;github.com/sagnik3788/dapper-go/pkg/proto/tracerpb;tracerpbb\x06proto3"

var (
	file_tracerpb_span_proto_rawDescOnce sync.Once
	file_tracerpb_span_proto_rawDescData []byte
)

func file_tracerpb_span_proto_rawDescGZIP() []byte {
	file_tracerpb_span_proto_rawDescOnce.Do(func() {
		file_tracerpb_span_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracerpb_span_proto_rawDesc), len(file_tracerpb_span_proto_rawDesc)))
	})
	return file_tracerpb_span_proto_rawDescData
}

var file_tracerpb_span_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tracerpb_span_proto_goTypes = []any{
	(*ExportRequest)(nil),  // 0: tracerpb.ExportRequest
	(*ExportResponse)(nil), // 1: tracerpb.ExportResponse
	(*Span)(nil),           // 2: tracerpb.Span
}
var file_tracerpb_span_proto_depIdxs = []int32{
	2, // 0: tracerpb.ExportRequest.spans:type_name -> tracerpb.Span
	0, // 1: tracerpb.Collector.Collect:input_type -> tracerpb.ExportRequest
	1, // 2: tracerpb.Collector.Collect:output_type -> tracerpb.ExportResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tracerpb_span_proto_init() }
func file_tracerpb_span_proto_init() {
	if File_tracerpb_span_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracerpb_span_proto_rawDesc), len(file_tracerpb_span_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tracerpb_span_proto_goTypes,
		DependencyIndexes: file_tracerpb_span_proto_depIdxs,
		MessageInfos:      file_tracerpb_span_proto_msgTypes,
	}.Build()
	File_tracerpb_span_proto = out.File
	file_tracerpb_span_proto_goTypes = nil
	file_tracerpb_span_proto_depIdxs = nil
}
